on: push
name: 🚀 Enviar a producción 
jobs:
  web-deploy:
    name: 🎉 Enviar
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obteniendo cambios
      uses: actions/checkout@v3
    
    - name: 📂 Sincronizando archivos 
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.cgmaquinaria.mx
        server-dir: public_html/
        username: cgmaquin
        password: ${{ secrets.FTP_PASSWORD }}